"""add_grid_position_to_rooms

Revision ID: 17532bfbf5a3
Revises: 9dfaedd2d793
Create Date: 2026-04-04 14:42:47.822482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17532bfbf5a3'
down_revision: Union[str, Sequence[str], None] = '9dfaedd2d793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('grid_row', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('grid_col', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'grid_col')
    op.drop_column('rooms', 'grid_row')
    # ### end Alembic commands ###
