"""add_grid_pane_to_rooms

Revision ID: 19011691cf50
Revises: 17532bfbf5a3
Create Date: 2026-04-04 14:52:28.280871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19011691cf50'
down_revision: Union[str, Sequence[str], None] = '17532bfbf5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('grid_pane', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'grid_pane')
    # ### end Alembic commands ###
