"""make schedule_entries room_id nullable

Revision ID: a79ee9f7d365
Revises: ed3afeb1d478
Create Date: 2026-04-02 12:59:50.058027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79ee9f7d365'
down_revision: Union[str, Sequence[str], None] = 'ed3afeb1d478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_entries', 'room_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_entries', 'room_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
