"""add primary_room_id to school_classes

Revision ID: d71d10d4c0b5
Revises: b8f6fead8f5c
Create Date: 2026-04-03 22:21:45.973096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71d10d4c0b5'
down_revision: Union[str, Sequence[str], None] = 'b8f6fead8f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('schedule_entries_class_id_fkey'), 'schedule_entries', type_='foreignkey')
    op.drop_constraint(op.f('schedule_entries_room_id_fkey'), 'schedule_entries', type_='foreignkey')
    op.drop_constraint(op.f('schedule_entries_timeslot_id_fkey'), 'schedule_entries', type_='foreignkey')
    op.drop_constraint(op.f('schedule_entries_teacher_id_fkey'), 'schedule_entries', type_='foreignkey')
    op.drop_constraint(op.f('schedule_entries_subject_id_fkey'), 'schedule_entries', type_='foreignkey')
    op.create_foreign_key(
        'fk_schedule_entries_subject_id_subjects',
        'schedule_entries',
        'subjects',
        ['subject_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_schedule_entries_class_id_school_classes',
        'schedule_entries',
        'school_classes',
        ['class_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_schedule_entries_timeslot_id_timeslots',
        'schedule_entries',
        'timeslots',
        ['timeslot_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_schedule_entries_teacher_id_teachers',
        'schedule_entries',
        'teachers',
        ['teacher_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_schedule_entries_room_id_rooms',
        'schedule_entries',
        'rooms',
        ['room_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.add_column('school_classes', sa.Column('primary_room_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_school_classes_primary_room_id_rooms',
        'school_classes',
        'rooms',
        ['primary_room_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_school_classes_primary_room_id_rooms', 'school_classes', type_='foreignkey')
    op.drop_column('school_classes', 'primary_room_id')
    op.drop_constraint('fk_schedule_entries_room_id_rooms', 'schedule_entries', type_='foreignkey')
    op.drop_constraint('fk_schedule_entries_teacher_id_teachers', 'schedule_entries', type_='foreignkey')
    op.drop_constraint('fk_schedule_entries_timeslot_id_timeslots', 'schedule_entries', type_='foreignkey')
    op.drop_constraint('fk_schedule_entries_class_id_school_classes', 'schedule_entries', type_='foreignkey')
    op.drop_constraint('fk_schedule_entries_subject_id_subjects', 'schedule_entries', type_='foreignkey')
    op.create_foreign_key(op.f('schedule_entries_subject_id_fkey'), 'schedule_entries', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('schedule_entries_teacher_id_fkey'), 'schedule_entries', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('schedule_entries_timeslot_id_fkey'), 'schedule_entries', 'timeslots', ['timeslot_id'], ['id'])
    op.create_foreign_key(op.f('schedule_entries_room_id_fkey'), 'schedule_entries', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('schedule_entries_class_id_fkey'), 'schedule_entries', 'school_classes', ['class_id'], ['id'])
    # ### end Alembic commands ###
