"""Add school_class entity and class_id FKs and period_type

Revision ID: ed3afeb1d478
Revises: 7ebb3dea076b
Create Date: 2026-04-02 12:02:19.732700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3afeb1d478'
down_revision: Union[str, Sequence[str], None] = '7ebb3dea076b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_classes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('contact_teacher_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contact_teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_class_name')
    )
    op.create_index(op.f('ix_school_classes_tenant_id'), 'school_classes', ['tenant_id'], unique=False)
    op.add_column('schedule_entries', sa.Column('class_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'schedule_entries', 'school_classes', ['class_id'], ['id'])
    op.add_column('subjects', sa.Column('class_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('uq_tenant_subject_grade'), 'subjects', type_='unique')
    op.create_unique_constraint('uq_tenant_subject_grade_class', 'subjects', ['tenant_id', 'name', 'grade_level', 'class_id'])
    op.create_foreign_key(None, 'subjects', 'school_classes', ['class_id'], ['id'])
    op.add_column('timeslots', sa.Column('period_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeslots', 'period_type')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint('uq_tenant_subject_grade_class', 'subjects', type_='unique')
    op.create_unique_constraint(op.f('uq_tenant_subject_grade'), 'subjects', ['tenant_id', 'name', 'grade_level'], postgresql_nulls_not_distinct=False)
    op.drop_column('subjects', 'class_id')
    op.drop_constraint(None, 'schedule_entries', type_='foreignkey')
    op.drop_column('schedule_entries', 'class_id')
    op.drop_index(op.f('ix_school_classes_tenant_id'), table_name='school_classes')
    op.drop_table('school_classes')
    # ### end Alembic commands ###
